# Generated by Django 4.2.3 on 2023-07-30 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DashboardApp', '0007_categories_slug_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=200)),
                ('JoinedAt', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('qty', models.CharField(default=1, max_length=50, null=True)),
                ('price', models.IntegerField()),
                ('Added_at', models.DateTimeField(auto_now=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteApp.user_data')),
            ],
        ),
    ]
