# Generated by Django 4.2.3 on 2023-07-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0007_categories_slug_products_slug'),
        ('SiteApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Cart',
            new_name='Cart',
        ),
    ]
