# Generated by Django 4.2.4 on 2023-08-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0004_rename_tracing_number_orders_items_orders_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_items',
            name='Orders_Status',
            field=models.IntegerField(choices=[(25, 'Order Confirm'), (50, 'Shipped'), (75, 'Out of Delevery'), (100, '4'), (0, 'Canceled')], default=25),
        ),
        migrations.AddField(
            model_name='orders_items',
            name='UpdatedAt',
            field=models.DateField(auto_now=True),
        ),
    ]
