# Generated by Django 4.2.4 on 2023-08-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0006_remove_orderaddress_orders_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_items',
            name='UpdatedAt',
        ),
        migrations.AddField(
            model_name='orders_items',
            name='order_status',
            field=models.IntegerField(default=25, max_length=150),
        ),
    ]
