# Generated by Django 4.2.4 on 2023-09-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0007_remove_orders_items_updatedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_items',
            name='order_status',
            field=models.IntegerField(choices=[(25, 'Confirmed'), (50, 'Shipped'), (75, 'Our for Delevery'), (100, 'Delevered'), (0, 'Cancel')], default=25),
        ),
    ]
