# Generated by Django 4.2.3 on 2023-07-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='Category_icon',
            field=models.FileField(default='null', upload_to='media/Categories/'),
        ),
    ]
