# Generated by Django 4.2.3 on 2023-07-23 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0003_alter_categories_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=50)),
                ('Item_image', models.ImageField(default='null', upload_to='media/Products/')),
                ('Total_price', models.IntegerField()),
                ('descount_price', models.IntegerField()),
                ('Qty', models.IntegerField()),
                ('Color', models.CharField(max_length=10)),
                ('Description', models.CharField(max_length=200)),
                ('Created_At', models.DateField(auto_now=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.categories')),
            ],
        ),
    ]
