# Generated by Django 4.2.3 on 2023-07-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0004_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Color',
        ),
    ]
