# Generated by Django 4.2.3 on 2023-07-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0005_remove_products_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.CharField(max_length=2000),
        ),
    ]
