# Generated by Django 4.2.3 on 2023-07-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0006_alter_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
